### ISSUE TITLE
3D Effect Not Working - Example 1

### ISSUE THREAD

**Issue by gngable** [LeiaInc/Leia_WebGL_SDK#6]
I installed the backlight switch apk on my Lume pad.
Then followed the instructions in the readme to build and serve the app.
When I navigate to the url on my Lume pad I see the rotating cube in example 1, but it looks very choppy and is not in 3D. I tried using both firefox and chrome. I also tried restarting the pad after installing the backlight switch apk. The app is built and hosted on Ubuntu 21.04.

**Comment by JoeLangLeiaInc** [comment]
Hello @gngable, thank you for the issue ticket! To best find a solution for you could you please try the following:

- Re-follow our online documentation and Example Project Tutorial using Three.js here https://docs.leialoft.com/developer/webgl-sdk/leia-webgl-sdk. We have recently updated our documentation and it is possible the updates may resolve your issue.
- If the issue persists, please record a screen shot of the broken visuals
